languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Sam's Blog"
logo = "img/logo.png"
description = "General Musings, Techincal Thoughts"
copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Sam Herring"
  image = "img/sam.png"
  bio = "I'm only human"
  headline = "Ocassionally Tecnical, Often Omnipotent"
  links = [
    { email = "mailto:samherring111@gmail.com" },
  #   { dev = "https://dev.to/username" },
    { github = "https://github.com/CapnSammeh" },
    { linkedin = "https://linkedin.com/in/sam-herring" },
  ]
