baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "m10c"

[params]
  author = "CapnSammeh"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula turpis sit amet elit pretium."
  [[params.social]]
    name = "github"
    url = "https://github.com/CapnSammeh"
