# Backend Config
backend:
  name: git-gateway
  repo: CapnSammeh/CapnSammeh-Blog
  branch: main
site_url: "https://samherring.netlify.app"

# Publish Mode
publish_mode: editorial_workflow

# Folders
media_folder: static/img
public_folder: /public/images

# Media Collections
media_library:
  name: cloudinary
  config:
    cloud_name: capnsammeh
    api_key: 524921581881768
    output_filename_only: false
    default_transformations:
      - - fetch_format: auto
          width: 400
          quality: auto
          crop: scale

# Other
show_preview_links: true

# Collections
collections:
  # Branch Pages
  - name: 'pages'
    label: 'Branch Pages'
    files: 
      - label: 'Posts Landing Page'
        name: 'posts'
        file: 'content/posts/_index.md'
        fields: 
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  
  # Posts Management
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: content/posts/
    path: '{{slug}}/index'
    create: true
    identifier_field: title
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    
    fields:
      - { label: "Show Comments", name: 'showComments', widget: 'hidden', default: true}
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true, required: false}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, allow_add: true }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false, default: '{{slug}}/featured.jpg' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false, media_folder: '{{slug}}' }
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
