backend:
  name: github
  repo: CapnSammeh/CapnSammeh-Blog
  branch: main
media_folder: static/img
public_folder: /public/images
show_preview_links: true
site_url: "http://samherring.netlify.app"
collections:
# https://www.netlifycms.org/docs/collection-types/
  - label: 'Pages'
    name: 'pages'
    create: true
    files: 
      - label: 'Home Page'
        name: 'homepage'
        file: 'content/_index.md'
        fields: 
          - {label: 'Draft', name: 'draft', widget: 'boolean'}
          - {label: 'Title', name: 'title', widget: 'string'}
          
      - label: 'Posts Index'
        name: 'post_index'
        file: 'content/posts/_index.md'
        fields: 
          - {label: 'Draft', name: 'draft', widget: 'boolean'}
          - {label: 'Title', name: 'title', widget: 'string'}
  - label: 'Blog Post'
    name: 'blog'
    folder: 'content/posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    filter: { field: 'showCMS', value: 'true' }
    preview_path: "posts/{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Show CMS", name: 'showCMS', widget: 'hidden', default: true}
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true, required: false}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Series', name: 'series', widget: 'list' }
      - { label: 'Series Order', name: 'series_order', widget: 'number', value_type: 'int' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, allow_add: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
