# Backend Config
backend:
  name: git-gateway
  repo: CapnSammeh/CapnSammeh-Blog
  branch: main
site_url: "https://samherring.netlify.app"

# Folders
media_folder: static/img
public_folder: /public/images

# Other
show_preview_links: false

# Collections
collections:
  # Branch Pages
  - name: 'pages'
    label: 'Branch Pages'
    files: 
      - label: 'Posts Landing Page'
        name: 'posts'
        file: 'content/posts/_index.md'
        fields: 
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  
  # Posts Management
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: /content/posts/
    path: '{{slug}}/index'
    create: true
    filter: {field: 'showCMS', value: true}
    
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    
    fields:
      - { label: "Show CMS", name: 'showCMS', widget: 'hidden', default: true}
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true, required: false}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, allow_add: true }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false, media_folder: '{{slug}}' }
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
