name: Nightly Merge of Content Branch

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge Content -> Main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: content
          target_branch: main
          github_token: ${{ github.token }}
